org: jb08brownie
app: nasa
service: nasa-daily-image
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - schedule: cron(30 5 * * ? *)
    environment:
      NASA_API_KEY: "REPLACE_WITH_YOUR_NASA_API_KEY"
      TWILIO_ACCOUNT_SID: "REPLACE_WITH_YOUR_TWILIO_ACCOUNT_SID"
      TWILIO_AUTH_TOKEN: "REPLACE_WITH_YOUR_TWILIO_ACCOUNT_AUTH_TOKEN"
      TWILIO_PHONE_NUMBER: "REPLACE_WITH_YOUR_TWILIO_PHONE_NUMBER"
      MY_PHONE_NUMBER: "REPLACE_WITH_YOUR_PHONE_NUMBER"